[package]
name = "pacifica"
version = "0.1.0"
authors = ["serinuntius <wasab1gj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
